/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author espaks
 */
public class Kalkulators extends javax.swing.JFrame {
    int firstNum = 0, secondNum = 0;
    float result = 0f;
    char event;
    int whichNum = 1;
    /**
     * Creates new form Kalkulators
     */
    public Kalkulators() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Skaitli = new javax.swing.JLabel();
        ButtonDivide = new javax.swing.JButton();
        ButtonMultiplication = new javax.swing.JButton();
        ButtonPlus = new javax.swing.JButton();
        ButtonMinus = new javax.swing.JButton();
        ButtonEquals = new javax.swing.JButton();
        SkaitluVieta = new javax.swing.JTextField();
        ButtonGoBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Skaitli.setText("1. skaitlis");
        Skaitli.setToolTipText("");
        Skaitli.setPreferredSize(new java.awt.Dimension(44, 18));

        ButtonDivide.setText("/");
        ButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivideActionPerformed(evt);
            }
        });

        ButtonGoBack.setText("Go Back to beginning");
        ButtonGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGoBackActionPerformed(evt);
            }
        });

        ButtonMultiplication.setText("*");
        ButtonMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplicationActionPerformed(evt);
            }
        });

        ButtonPlus.setText("+");
        ButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlusActionPerformed(evt);
            }
        });

        ButtonMinus.setText("-");
        ButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinusActionPerformed(evt);
            }
        });

        ButtonEquals.setText("=");
        ButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualsActionPerformed(evt);
            }
        });

        SkaitluVieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkaitluVietaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Skaitli, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ButtonGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SkaitluVieta))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Skaitli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SkaitluVieta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                        .addComponent(ButtonGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SkaitluVietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkaitluVietaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SkaitluVietaActionPerformed

    private void ButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinusActionPerformed
        if (whichNum != 3){
            event = '-';
            if (whichNum == 1){
                firstNum = Integer.parseInt(SkaitluVieta.getText());
                Skaitli.setText("2. skaitlis");
            }
            whichNum++;
            SkaitluVieta.setText("");
        }
//        if(whichNum == 10){
//            Skaitli.setText("Nedrīkst ievast vairāk par 10 skaitļiem!");
//            ButtonEqualsActionPerformed(evt);
//        }
//        allNumbers[whichNum-1] = Integer.parseInt(SkaitluVieta.getText());
//        event = '-';
//        if (whichNum != 1){
//            SkaitluVieta.setText(Integer.parseInt(SkaitluVieta.getText()) - Integer.parseInt(SkaitluVieta.getText()) + "");
//        }
//        Skaitli.setText(whichNum+1+". skaitlis");
//        whichNum++;
//        SkaitluVieta.setText("");
        
    }//GEN-LAST:event_ButtonMinusActionPerformed

    private void ButtonMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplicationActionPerformed
        if (whichNum != 3){
            event = '*';
            if (whichNum == 1){
                firstNum = Integer.parseInt(SkaitluVieta.getText());
                Skaitli.setText("2. skaitlis");
            }
            whichNum++;
            SkaitluVieta.setText("");
        }
    }//GEN-LAST:event_ButtonMultiplicationActionPerformed

    private void ButtonGoBackActionPerformed(java.awt.event.ActionEvent evt){
        whichNum = 1;
        Skaitli.setText("1. skaitlis");
        SkaitluVieta.setText("");
    }//GEN-LAST:event_ButtonGoBackActionPerformed

    private void ButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlusActionPerformed
        if (whichNum != 3){
            event = '+';
            if (whichNum == 1){
                firstNum = Integer.parseInt(SkaitluVieta.getText());
                Skaitli.setText("2. skaitlis");
            }
            whichNum++;
            SkaitluVieta.setText("");
        }
    }//GEN-LAST:event_ButtonPlusActionPerformed

    private void ButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualsActionPerformed
        if (whichNum != 1){
            if (whichNum == 2){
                secondNum = Integer.parseInt(SkaitluVieta.getText());
            }
            switch (event){
                case '+':
                    result = firstNum + secondNum;
                    break;
                case '-':
                    result = firstNum - secondNum;
                    break;
                case '/':
                    result = (float)firstNum / (float)secondNum;
                    break;
                case '*':
                    result = firstNum * secondNum;
            }
            Skaitli.setText("Rezultāts");
            if (event != '/'){
                SkaitluVieta.setText((int)result+"");
            } else {
                SkaitluVieta.setText(result+"");
            }
        }
        else {
            Skaitli.setText("No sākuma izvēlēties darbību        1.skaitlis");
        }
    }//GEN-LAST:event_ButtonEqualsActionPerformed

    private void ButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivideActionPerformed
        if (whichNum != 3){
            event = '/';
            if (whichNum == 1){
                firstNum = Integer.parseInt(SkaitluVieta.getText());
                Skaitli.setText("2. skaitlis");
            }
            whichNum++;
            SkaitluVieta.setText("");
        }
    }//GEN-LAST:event_ButtonDivideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulators().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDivide;
    private javax.swing.JButton ButtonEquals;
    private javax.swing.JButton ButtonMinus;
    private javax.swing.JButton ButtonMultiplication;
    private javax.swing.JButton ButtonPlus;
    private javax.swing.JButton ButtonGoBack;
    private javax.swing.JLabel Skaitli;
    private javax.swing.JTextField SkaitluVieta;
    // End of variables declaration//GEN-END:variables
}
